"""Strategy parameter registry."""

from .strategy_params_base import (
    ParameterDefinition,
    StrategyName,
    StrategyParameterConfig,
)


# ============================================================================
# STRATEGY PARAMETER REGISTRY
# ============================================================================

STRATEGY_PARAMETER_REGISTRY: dict[StrategyName, StrategyParameterConfig] = {
    # -------------------------------------------------------------------------
    # BREAKOUT STRATEGY
    # -------------------------------------------------------------------------
    StrategyName.BREAKOUT: StrategyParameterConfig(
        strategy_name=StrategyName.BREAKOUT,
        display_name="Breakout",
        description="Breakout strategy using support/resistance levels and volume confirmation.",
        parameters=[
            ParameterDefinition(
                name="sr_window",
                display_name="S/R Window",
                param_type="int",
                default=20,
                min_value=10,
                max_value=50,
                step=5,
                description="Window size for support/resistance detection",
            ),
            ParameterDefinition(
                name="sr_levels",
                display_name="S/R Levels",
                param_type="int",
                default=3,
                min_value=1,
                max_value=5,
                step=1,
                description="Number of support/resistance levels to detect",
            ),
            ParameterDefinition(
                name="atr_period",
                display_name="ATR Period",
                param_type="int",
                default=14,
                min_value=5,
                max_value=30,
                step=1,
                description="Period for Average True Range calculation",
            ),
            ParameterDefinition(
                name="adx_period",
                display_name="ADX Period",
                param_type="int",
                default=14,
                min_value=5,
                max_value=30,
                step=1,
                description="Period for ADX trend strength indicator",
            ),
            ParameterDefinition(
                name="adx_threshold",
                display_name="ADX Threshold",
                param_type="int",
                default=25,
                min_value=15,
                max_value=40,
                step=5,
                description="Minimum ADX value for trend confirmation",
            ),
            ParameterDefinition(
                name="volume_ratio",
                display_name="Volume Ratio",
                param_type="float",
                default=1.5,
                min_value=1.0,
                max_value=3.0,
                step=0.1,
                description="Required volume ratio above average",
            ),
            ParameterDefinition(
                name="price_change_pct",
                display_name="Min Price Change %",
                param_type="float",
                default=0.01,
                min_value=0.005,
                max_value=0.05,
                step=0.005,
                description="Minimum price change percentage for breakout",
            ),
        ],
    ),
    # -------------------------------------------------------------------------
    # MOMENTUM STRATEGY
    # -------------------------------------------------------------------------
    StrategyName.MOMENTUM: StrategyParameterConfig(
        strategy_name=StrategyName.MOMENTUM,
        display_name="Momentum",
        description="Momentum strategy using ROC, MOM, OBV, and RSI indicators.",
        parameters=[
            ParameterDefinition(
                name="roc_period",
                display_name="ROC Period",
                param_type="int",
                default=10,
                min_value=5,
                max_value=20,
                step=1,
                description="Period for Rate of Change indicator",
            ),
            ParameterDefinition(
                name="mom_period",
                display_name="Momentum Period",
                param_type="int",
                default=10,
                min_value=5,
                max_value=20,
                step=1,
                description="Period for Momentum indicator",
            ),
            ParameterDefinition(
                name="rsi_period",
                display_name="RSI Period",
                param_type="int",
                default=14,
                min_value=7,
                max_value=21,
                step=1,
                description="Period for RSI calculation",
            ),
            ParameterDefinition(
                name="roc_threshold",
                display_name="ROC Threshold",
                param_type="float",
                default=5.0,
                min_value=2.0,
                max_value=10.0,
                step=1.0,
                description="Minimum ROC value for entry",
            ),
            ParameterDefinition(
                name="obv_change_threshold",
                display_name="OBV Change %",
                param_type="float",
                default=5.0,
                min_value=2.0,
                max_value=15.0,
                step=1.0,
                description="Minimum OBV change percentage",
            ),
            ParameterDefinition(
                name="rsi_lower",
                display_name="RSI Lower",
                param_type="int",
                default=50,
                min_value=40,
                max_value=60,
                step=5,
                description="Lower RSI threshold for entry",
            ),
            ParameterDefinition(
                name="rsi_upper",
                display_name="RSI Upper",
                param_type="int",
                default=80,
                min_value=70,
                max_value=90,
                step=5,
                description="Upper RSI threshold for entry",
            ),
            ParameterDefinition(
                name="rsi_exit_threshold",
                display_name="RSI Exit",
                param_type="int",
                default=85,
                min_value=75,
                max_value=95,
                step=5,
                description="RSI threshold for exit signal",
            ),
        ],
    ),
    # -------------------------------------------------------------------------
    # MEAN REVERSION STRATEGY
    # -------------------------------------------------------------------------
    StrategyName.MEAN_REVERSION: StrategyParameterConfig(
        strategy_name=StrategyName.MEAN_REVERSION,
        display_name="Mean Reversion",
        description="Mean reversion strategy using Bollinger Bands and RSI for oversold/overbought conditions.",
        parameters=[
            ParameterDefinition(
                name="bb_period",
                display_name="BB Period",
                param_type="int",
                default=20,
                min_value=10,
                max_value=40,
                step=5,
                description="Period for Bollinger Bands",
            ),
            ParameterDefinition(
                name="bb_std",
                display_name="BB Std Dev",
                param_type="float",
                default=2.0,
                min_value=1.5,
                max_value=3.0,
                step=0.25,
                description="Standard deviation multiplier for Bollinger Bands",
            ),
            ParameterDefinition(
                name="rsi_period",
                display_name="RSI Period",
                param_type="int",
                default=14,
                min_value=7,
                max_value=21,
                step=1,
                description="Period for RSI calculation",
            ),
            ParameterDefinition(
                name="rsi_oversold",
                display_name="RSI Oversold",
                param_type="int",
                default=30,
                min_value=20,
                max_value=40,
                step=5,
                description="RSI threshold for oversold condition",
            ),
            ParameterDefinition(
                name="rsi_overbought",
                display_name="RSI Overbought",
                param_type="int",
                default=70,
                min_value=60,
                max_value=80,
                step=5,
                description="RSI threshold for overbought condition",
            ),
            ParameterDefinition(
                name="bb_percent_entry",
                display_name="BB% Entry",
                param_type="float",
                default=0.1,
                min_value=0.0,
                max_value=0.3,
                step=0.05,
                description="Maximum BB% for entry (0=lower band, 1=upper band)",
            ),
            ParameterDefinition(
                name="bb_percent_exit",
                display_name="BB% Exit",
                param_type="float",
                default=0.9,
                min_value=0.7,
                max_value=1.0,
                step=0.05,
                description="Minimum BB% for exit",
            ),
        ],
    ),
    # -------------------------------------------------------------------------
    # TREND FOLLOWING STRATEGY
    # -------------------------------------------------------------------------
    StrategyName.TREND_FOLLOWING: StrategyParameterConfig(
        strategy_name=StrategyName.TREND_FOLLOWING,
        display_name="Trend Following",
        description="Trend following strategy using SMA crossovers, RSI, and MACD confirmation.",
        parameters=[
            ParameterDefinition(
                name="sma_fast",
                display_name="SMA Fast",
                param_type="int",
                default=50,
                min_value=20,
                max_value=100,
                step=10,
                description="Period for fast Simple Moving Average",
            ),
            ParameterDefinition(
                name="sma_slow",
                display_name="SMA Slow",
                param_type="int",
                default=200,
                min_value=100,
                max_value=300,
                step=20,
                description="Period for slow Simple Moving Average",
            ),
            ParameterDefinition(
                name="rsi_period",
                display_name="RSI Period",
                param_type="int",
                default=14,
                min_value=7,
                max_value=21,
                step=1,
                description="Period for RSI calculation",
            ),
            ParameterDefinition(
                name="rsi_upper_limit",
                display_name="RSI Upper Limit",
                param_type="int",
                default=70,
                min_value=60,
                max_value=80,
                step=5,
                description="Maximum RSI for entry (avoid overbought)",
            ),
            ParameterDefinition(
                name="rsi_lower_limit",
                display_name="RSI Lower Limit",
                param_type="int",
                default=30,
                min_value=20,
                max_value=40,
                step=5,
                description="Minimum RSI for exit signal",
            ),
            ParameterDefinition(
                name="macd_fast",
                display_name="MACD Fast",
                param_type="int",
                default=12,
                min_value=8,
                max_value=16,
                step=1,
                description="Fast period for MACD",
            ),
            ParameterDefinition(
                name="macd_slow",
                display_name="MACD Slow",
                param_type="int",
                default=26,
                min_value=20,
                max_value=32,
                step=2,
                description="Slow period for MACD",
            ),
            ParameterDefinition(
                name="macd_signal",
                display_name="MACD Signal",
                param_type="int",
                default=9,
                min_value=7,
                max_value=12,
                step=1,
                description="Signal period for MACD",
            ),
        ],
    ),
    # -------------------------------------------------------------------------
    # SCALPING STRATEGY
    # -------------------------------------------------------------------------
    StrategyName.SCALPING: StrategyParameterConfig(
        strategy_name=StrategyName.SCALPING,
        display_name="Scalping",
        description="High-frequency scalping strategy using EMA crossovers, VWAP, and Stochastic.",
        parameters=[
            ParameterDefinition(
                name="ema_fast",
                display_name="EMA Fast",
                param_type="int",
                default=5,
                min_value=3,
                max_value=10,
                step=1,
                description="Period for fast EMA",
            ),
            ParameterDefinition(
                name="ema_slow",
                display_name="EMA Slow",
                param_type="int",
                default=9,
                min_value=7,
                max_value=15,
                step=1,
                description="Period for slow EMA",
            ),
            ParameterDefinition(
                name="stoch_k",
                display_name="Stochastic K",
                param_type="int",
                default=5,
                min_value=3,
                max_value=10,
                step=1,
                description="K period for Stochastic oscillator",
            ),
            ParameterDefinition(
                name="stoch_d",
                display_name="Stochastic D",
                param_type="int",
                default=3,
                min_value=2,
                max_value=5,
                step=1,
                description="D period for Stochastic oscillator",
            ),
            ParameterDefinition(
                name="stoch_upper",
                display_name="Stoch Upper",
                param_type="int",
                default=80,
                min_value=70,
                max_value=90,
                step=5,
                description="Upper Stochastic threshold",
            ),
            ParameterDefinition(
                name="stoch_lower",
                display_name="Stoch Lower",
                param_type="int",
                default=20,
                min_value=10,
                max_value=30,
                step=5,
                description="Lower Stochastic threshold",
            ),
            ParameterDefinition(
                name="max_spread_pct",
                display_name="Max Spread %",
                param_type="float",
                default=0.5,
                min_value=0.1,
                max_value=1.0,
                step=0.1,
                description="Maximum allowed spread percentage",
            ),
            ParameterDefinition(
                name="min_hold_seconds",
                display_name="Min Hold (sec)",
                param_type="int",
                default=60,
                min_value=30,
                max_value=300,
                step=30,
                description="Minimum holding time in seconds",
            ),
        ],
    ),
    # -------------------------------------------------------------------------
    # BOLLINGER SQUEEZE BREAKOUT
    # -------------------------------------------------------------------------
    StrategyName.BOLLINGER_SQUEEZE: StrategyParameterConfig(
        strategy_name=StrategyName.BOLLINGER_SQUEEZE,
        display_name="Bollinger Squeeze",
        description="Explosive breakout strategy after low volatility squeeze.",
        parameters=[
            ParameterDefinition("bb_period", "BB Period", "int", 20, 10, 50, 5, "Period for Bollinger Bands"),
            ParameterDefinition("bb_std", "BB Std", "float", 2.0, 1.5, 3.0, 0.1, "Standard deviation for BB"),
            ParameterDefinition("kc_atr_period", "KC ATR Period", "int", 10, 5, 20, 1, "ATR Period for Keltner Channels"),
            ParameterDefinition("kc_multiplier", "KC Multiplier", "float", 1.5, 1.0, 2.5, 0.1, "Multiplier for Keltner Channels"),
            ParameterDefinition("vol_period", "Vol Period", "int", 20, 10, 50, 5, "Volume MA Period"),
            ParameterDefinition("vol_factor", "Vol Factor", "float", 1.5, 1.1, 3.0, 0.1, "Volume Spike Factor"),
        ],
    ),
    # -------------------------------------------------------------------------
    # TREND PULLBACK
    # -------------------------------------------------------------------------
    StrategyName.TREND_PULLBACK: StrategyParameterConfig(
        strategy_name=StrategyName.TREND_PULLBACK,
        display_name="Trend Pullback",
        description="Classic trend following: Buy dips in uptrends.",
        parameters=[
            ParameterDefinition("ema_trend", "EMA Trend", "int", 200, 50, 200, 10, "Trend Filter EMA"),
            ParameterDefinition("rsi_period", "RSI Period", "int", 14, 7, 21, 1, "RSI Period"),
            ParameterDefinition("rsi_pullback", "RSI Pullback", "int", 40, 20, 50, 5, "RSI Level for Pullback Entry"),
            ParameterDefinition("rsi_exit", "RSI Exit", "int", 70, 60, 80, 5, "RSI Level for Exit"),
        ],
    ),
    # -------------------------------------------------------------------------
    # OPENING RANGE BREAKOUT
    # -------------------------------------------------------------------------
    StrategyName.OPENING_RANGE: StrategyParameterConfig(
        strategy_name=StrategyName.OPENING_RANGE,
        display_name="Opening Range",
        description="Trades the breakout of the opening range.",
        parameters=[
            ParameterDefinition("range_minutes", "Range (min)", "int", 15, 5, 60, 5, "Minutes to define opening range"),
            ParameterDefinition("vol_factor", "Vol Factor", "float", 1.5, 1.1, 3.0, 0.1, "Volume Spike Factor"),
            ParameterDefinition("atr_period", "ATR Period", "int", 14, 5, 30, 1, "ATR Period"),
        ],
    ),
    # -------------------------------------------------------------------------
    # REGIME SWITCHING HYBRID
    # -------------------------------------------------------------------------
    StrategyName.REGIME_HYBRID: StrategyParameterConfig(
        strategy_name=StrategyName.REGIME_HYBRID,
        display_name="Regime Hybrid",
        description="Switches strategies based on market regime (Trend/Range/Vol).",
        parameters=[
            ParameterDefinition("adx_period", "ADX Period", "int", 14, 7, 21, 1, "ADX Period"),
            ParameterDefinition("trend_threshold", "Trend Thresh", "int", 25, 15, 35, 5, "ADX Threshold for Trend"),
            ParameterDefinition("range_threshold", "Range Thresh", "int", 20, 10, 30, 5, "ADX Threshold for Range"),
            ParameterDefinition("bb_period", "BB Period", "int", 20, 10, 50, 5, "Bollinger Period"),
            ParameterDefinition("bb_std", "BB Std", "float", 2.0, 1.5, 2.5, 0.1, "Bollinger Std Dev"),
        ],
    ),
}
